In [1]:
# load all_the_features_combined_df.pkl

import pandas as pd

all_the_features_combined_df = pd.read_pickle('all_the_features_combined_df.pkl')

In [5]:
all_the_features_combined_df.head(5)

,minutes,score_difference,distance_to_goal,angle_to_goal,foul_count_player,foul_count_team,vaep_offensive,prediction_regressor,prediction_classifier,actual_label
id,,,,,,,,,,
a40924e7-b5ca-4f23-9025-ac535d63dab8,-1.804209,-0.352575,0.562204,-0.705381,-0.481498,-1.090844,0.207948,0.987373,1,1
24f49483-d437-40c2-bf5f-c6b3e5456d48,-1.613191,-0.352575,0.916698,0.828595,-0.481498,-0.761528,0.176081,0.931479,1,1
681f5c57-ed69-4bae-82e7-6d97233fb907,0.144183,-0.352575,-1.528967,2.990464,-0.481498,-0.102896,0.173477,0.920259,1,1
7ea7ec5e-388e-4b20-8ab5-d2359cb92a65,0.908258,-0.352575,1.798029,-0.033659,-0.481498,0.226419,-2.320992,0.914307,1,1
6238286d-a363-4ed3-abab-f322e0571e2d,0.182387,-0.352575,0.682044,-0.990849,-0.481498,-0.761528,0.203386,0.885819,1,1

In [3]:
# load all_fouls.pkl and testing_fouls.pkl

all_fouls = pd.read_pickle('all_fouls.pkl')

testing_fouls = pd.read_pickle('testing_fouls.pkl')

In [4]:
# combine all_fouls and testing_fouls into fouls

fouls = pd.concat([all_fouls, testing_fouls])

In [12]:
fouls.head(15)

,foul_committed_advantage,foul_committed_offensive,foul_committed_penalty,foul_committed_card,foul_committed_counterpress,foul_committed_type,foul_won_advantage,foul_won_defensive,foul_won_penalty,id,...,player,player_id,position,possession,possession_team,possession_team_id,team,team_id,timestamp,type
0,NaN,NaN,True,NaN,NaN,Handball,NaN,NaN,NaN,8ff4ccaf-29e0-4476-bd12-3d0bfd45d510,...,Moussa Sissoko,3091.0,Right Defensive Midfield,2,Liverpool,24,Tottenham Hotspur,38,00:00:22.971,Foul Committed
1,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a40924e7-b5ca-4f23-9025-ac535d63dab8,...,Sadio Mané,3629.0,Left Wing,4,Tottenham Hotspur,38,Liverpool,24,00:03:01.342,Foul Committed
2,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24f49483-d437-40c2-bf5f-c6b3e5456d48,...,Roberto Firmino Barbosa de Oliveira,3535.0,Center Forward,15,Tottenham Hotspur,38,Liverpool,24,00:08:26.201,Foul Committed
3,NaN,NaN,NaN,NaN,NaN,Handball,NaN,NaN,NaN,a3c1f5b5-f337-4077-8d9e-7388a6864241,...,Fábio Henrique Tavares,3247.0,Center Defensive Midfield,74,Liverpool,24,Liverpool,24,00:43:05.439,Foul Committed
4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,681f5c57-ed69-4bae-82e7-6d97233fb907,...,Trent Alexander-Arnold,3664.0,Right Back,103,Tottenham Hotspur,38,Liverpool,24,00:09:30.708,Foul Committed
5,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7ea7ec5e-388e-4b20-8ab5-d2359cb92a65,...,Divock Okoth Origi,4747.0,Center Forward,130,Tottenham Hotspur,38,Liverpool,24,00:29:47.540,Foul Committed
6,NaN,True,NaN,NaN,NaN,Handball,NaN,NaN,NaN,5f9542d8-4c95-408a-b2e8-49219568588c,...,Heung-Min Son,3083.0,Right Center Forward,131,Tottenham Hotspur,38,Tottenham Hotspur,38,00:30:30.090,Foul Committed
7,NaN,NaN,NaN,NaN,NaN,Handball,NaN,NaN,NaN,0b3be920-f109-4d98-847e-7576371fd18f,...,Roberto Firmino Barbosa de Oliveira,3535.0,Center Forward,75,Real Madrid,220,Liverpool,24,00:43:26.785,Foul Committed
8,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6238286d-a363-4ed3-abab-f322e0571e2d,...,Andrew Robertson,3655.0,Left Back,103,Real Madrid,220,Liverpool,24,00:10:42.470,Foul Committed
9,NaN,NaN,NaN,NaN,NaN,Handball,NaN,NaN,NaN,45e98d4f-4902-4d21-b8a1-b55677d46497,...,Adam David Lallana,4090.0,Left Wing,135,Liverpool,24,Liverpool,24,00:30:33.030,Foul Committed
10,NaN,NaN,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,928a15d8-a10e-411c-953d-301663f2fada,...,Sadio Mané,3629.0,Right Wing,146,Real Madrid,220,Liverpool,24,00:36:43.357,Foul Committed
11,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d32eb3eb-ac10-4d1f-a2d6-1f7d1b1f035c,...,Andrew Robertson,3655.0,Left Back,164,Real Madrid,220,Liverpool,24,00:47:26.547,Foul Committed
12,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,caaeb0e8-e589-4586-bf9c-56f0e75d1adf,...,Miralem Pjanić,6947.0,Right Defensive Midfield,40,Juventus,224,Juventus,224,00:10:46.156,Foul Committed
13,NaN,NaN,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,53666edb-be25-4515-ab85-23b572e06721,...,Paulo Bruno Exequiel Dybala,5743.0,Center Attacking Midfield,40,Juventus,224,Juventus,224,00:11:09.602,Foul Committed
14,NaN,True,NaN,NaN,NaN,Handball,NaN,NaN,NaN,91c4e53e-ca9c-4751-a3f4-5f281b884a72,...,Karim Benzema,19677.0,Right Center Forward,41,Real Madrid,220,Real Madrid,220,00:12:09.456,Foul Committed

In [13]:
# set 'id' as index for fouls

fouls.set_index('id', inplace=True)

In [15]:
# in all_the_features_combined_df, create a columns called 'match_id', 'possession_team_id', 'possesion_team', 'player_id', 'player'. Fill it from the fouls dataframe. Both dataframes have 'id' as its index.

all_the_features_combined_df['match_id'] = fouls['match_id']

all_the_features_combined_df['possession_team_id'] = fouls['possession_team_id']

all_the_features_combined_df['possession_team'] = fouls['possession_team']

all_the_features_combined_df['player_id'] = fouls['player_id']

all_the_features_combined_df['player'] = fouls['player']

In [22]:
# remove columns: foul_committed_advantage	foul_committed_offensive	foul_committed_penalty	foul_committed_card	foul_committed_counterpress	foul_committed_type	foul_won_advantage	foul_won_defensive	foul_won_penalty from fouls dataframe and save it as fouls_short

fouls_short = fouls.drop(['foul_committed_advantage', 'foul_committed_offensive', 'foul_committed_penalty', 'foul_committed_card', 'foul_committed_counterpress', 'foul_committed_type', 'foul_won_advantage', 'foul_won_defensive', 'foul_won_penalty'], axis=1)

fouls_short.head(10)

,index,location,match_id,minute,second,period,player,player_id,position,possession,possession_team,possession_team_id,team,team_id,timestamp,type
id,,,,,,,,,,,,,,,,
8ff4ccaf-29e0-4476-bd12-3d0bfd45d510,33,"[15.7, 54.2]",22912,0,22,1,Moussa Sissoko,3091.0,Right Defensive Midfield,2,Liverpool,24,Tottenham Hotspur,38,00:00:22.971,Foul Committed
a40924e7-b5ca-4f23-9025-ac535d63dab8,58,"[71.6, 18.0]",22912,3,1,1,Sadio Mané,3629.0,Left Wing,4,Tottenham Hotspur,38,Liverpool,24,00:03:01.342,Foul Committed
24f49483-d437-40c2-bf5f-c6b3e5456d48,291,"[77.5, 68.8]",22912,8,26,1,Roberto Firmino Barbosa de Oliveira,3535.0,Center Forward,15,Tottenham Hotspur,38,Liverpool,24,00:08:26.201,Foul Committed
a3c1f5b5-f337-4077-8d9e-7388a6864241,1456,"[78.6, 41.3]",22912,43,5,1,Fábio Henrique Tavares,3247.0,Center Defensive Midfield,74,Liverpool,24,Liverpool,24,00:43:05.439,Foul Committed
681f5c57-ed69-4bae-82e7-6d97233fb907,1993,"[8.4, 67.8]",22912,54,30,2,Trent Alexander-Arnold,3664.0,Right Back,103,Tottenham Hotspur,38,Liverpool,24,00:09:30.708,Foul Committed
7ea7ec5e-388e-4b20-8ab5-d2359cb92a65,2640,"[102.0, 38.8]",22912,74,47,2,Divock Okoth Origi,4747.0,Center Forward,130,Tottenham Hotspur,38,Liverpool,24,00:29:47.540,Foul Committed
5f9542d8-4c95-408a-b2e8-49219568588c,2682,"[110.0, 21.5]",22912,75,30,2,Heung-Min Son,3083.0,Right Center Forward,131,Tottenham Hotspur,38,Tottenham Hotspur,38,00:30:30.090,Foul Committed
0b3be920-f109-4d98-847e-7576371fd18f,1748,"[50.3, 25.0]",18245,43,26,1,Roberto Firmino Barbosa de Oliveira,3535.0,Center Forward,75,Real Madrid,220,Liverpool,24,00:43:26.785,Foul Committed
6238286d-a363-4ed3-abab-f322e0571e2d,2182,"[70.8, 8.4]",18245,55,42,2,Andrew Robertson,3655.0,Left Back,103,Real Madrid,220,Liverpool,24,00:10:42.470,Foul Committed
45e98d4f-4902-4d21-b8a1-b55677d46497,2894,"[77.8, 67.4]",18245,75,33,2,Adam David Lallana,4090.0,Left Wing,135,Liverpool,24,Liverpool,24,00:30:33.030,Foul Committed

In [21]:
all_the_features_combined_df.head(10)

,minutes,score_difference,distance_to_goal,angle_to_goal,foul_count_player,foul_count_team,vaep_offensive,prediction_regressor,prediction_classifier,actual_label,match_id,possession_team_id,possession_team,player_id,player
id,,,,,,,,,,,,,,,
a40924e7-b5ca-4f23-9025-ac535d63dab8,-1.804209,-0.352575,0.562204,-0.705381,-0.481498,-1.090844,0.207948,0.987373,1,1,22912,38,Tottenham Hotspur,3629.0,Sadio Mané
24f49483-d437-40c2-bf5f-c6b3e5456d48,-1.613191,-0.352575,0.916698,0.828595,-0.481498,-0.761528,0.176081,0.931479,1,1,22912,38,Tottenham Hotspur,3535.0,Roberto Firmino Barbosa de Oliveira
681f5c57-ed69-4bae-82e7-6d97233fb907,0.144183,-0.352575,-1.528967,2.990464,-0.481498,-0.102896,0.173477,0.920259,1,1,22912,38,Tottenham Hotspur,3664.0,Trent Alexander-Arnold
7ea7ec5e-388e-4b20-8ab5-d2359cb92a65,0.908258,-0.352575,1.798029,-0.033659,-0.481498,0.226419,-2.320992,0.914307,1,1,22912,38,Tottenham Hotspur,4747.0,Divock Okoth Origi
6238286d-a363-4ed3-abab-f322e0571e2d,0.182387,-0.352575,0.682044,-0.990849,-0.481498,-0.761528,0.203386,0.885819,1,1,18245,220,Real Madrid,3655.0,Andrew Robertson
928a15d8-a10e-411c-953d-301663f2fada,1.175685,-0.352575,0.848268,0.966531,-0.481498,-0.102896,0.089927,-0.030963,0,0,18245,220,Real Madrid,3629.0,Sadio Mané
d32eb3eb-ac10-4d1f-a2d6-1f7d1b1f035c,1.595926,-0.352575,0.994297,-0.894551,1.160428,0.226419,0.173065,0.964202,1,1,18245,220,Real Madrid,3655.0,Andrew Robertson
caaeb0e8-e589-4586-bf9c-56f0e75d1adf,-1.536783,0.674908,-0.884033,-0.223656,-0.481498,-1.090844,0.223001,1.017651,1,1,18244,224,Juventus,6947.0,Miralem Pjanić
53666edb-be25-4515-ab85-23b572e06721,-1.498579,0.674908,0.366500,-0.508221,-0.481498,-0.761528,-0.031811,0.617399,1,0,18244,224,Juventus,5743.0,Paulo Bruno Exequiel Dybala
214c40b2-a542-469e-9b9d-2b3ac936ccf8,-0.772708,-0.352575,-0.390512,-0.049499,-0.481498,-0.432212,-0.079687,0.432729,0,0,18244,224,Juventus,5201.0,Sergio Ramos García

In [23]:
# save all_the_features_combined_df as all_the_features_combined_df_more.pkl

all_the_features_combined_df.to_pickle('all_the_features_combined_df_more.pkl')

In [25]:
# all_the_features_combined_df where the match_id is 22912

all_the_features_combined_df[all_the_features_combined_df['match_id'] == 22912].head()

,minutes,score_difference,distance_to_goal,angle_to_goal,foul_count_player,foul_count_team,vaep_offensive,prediction_regressor,prediction_classifier,actual_label,match_id,possession_team_id,possession_team,player_id,player
id,,,,,,,,,,,,,,,
a40924e7-b5ca-4f23-9025-ac535d63dab8,-1.804209,-0.352575,0.562204,-0.705381,-0.481498,-1.090844,0.207948,0.987373,1,1,22912,38,Tottenham Hotspur,3629.0,Sadio Mané
24f49483-d437-40c2-bf5f-c6b3e5456d48,-1.613191,-0.352575,0.916698,0.828595,-0.481498,-0.761528,0.176081,0.931479,1,1,22912,38,Tottenham Hotspur,3535.0,Roberto Firmino Barbosa de Oliveira
681f5c57-ed69-4bae-82e7-6d97233fb907,0.144183,-0.352575,-1.528967,2.990464,-0.481498,-0.102896,0.173477,0.920259,1,1,22912,38,Tottenham Hotspur,3664.0,Trent Alexander-Arnold
7ea7ec5e-388e-4b20-8ab5-d2359cb92a65,0.908258,-0.352575,1.798029,-0.033659,-0.481498,0.226419,-2.320992,0.914307,1,1,22912,38,Tottenham Hotspur,4747.0,Divock Okoth Origi

In [26]:
all_the_features_combined_df['match_id'].value_counts()

68322      26
69308      25
68323      25
69299      21
70300      20
           ..
3857274     1
16215       1
3857273     1
3857262     1
3795187     1
Name: match_id, Length: 750, dtype: int64

In [35]:
from statsbombpy import sb

comp = sb.competitions()
comp = comp[comp.season_name != '1999/2000']

all_matches = pd.DataFrame()

for index, row in comp.iterrows():
    matches = sb.matches(row['competition_id'], row['season_id'])
    all_matches = all_matches.append(matches)

/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/tmp/ipykernel_12053/3622438590.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_matches = all_matches.append(matches)

In [38]:
# all_matches where match_id is 68322

all_matches[all_matches['match_id'] == 22912].head(30)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,22912,2019-06-01,21:00:00.000,Europe - Champions League,2018/2019,Tottenham Hotspur,Liverpool,0,2,available,...,2021-06-13T16:17:31.694,13,Final,Estádio Cívitas Metropolitano,Damir Skomina,Mauricio Roberto Pochettino Trossero,Jürgen Klopp,1.1.0,2,2

In [47]:
# which possession_team attracts foul at high prediction_regressor?

all_the_features_combined_df[all_the_features_combined_df['prediction_regressor'] > 0.8]['possession_team'].value_counts()

Barcelona              1840
Arsenal                 102
Real Madrid              73
England                  54
Atlético Madrid          54
                       ...
Inter Milan               1
Gimnàstic Tarragona       1
Slovakia                  1
Juventus                  1
Real Murcia CF            1
Name: possession_team, Length: 113, dtype: int64

In [48]:
# which possession_team attracts foul at low prediction_regressor?

all_the_features_combined_df[all_the_features_combined_df['prediction_regressor'] < 0.2]['possession_team'].value_counts()

Barcelona          909
Arsenal             45
Real Madrid         43
Atlético Madrid     41
Sevilla             39
                  ...
Finland              1
Scotland             1
Tenerife             1
Hércules             1
Iran                 1
Name: possession_team, Length: 97, dtype: int64

In [71]:
# Count count of unique match_id in all_the_features_combined_df by possession_team and display it as a dataframe in descending order

print(all_the_features_combined_df.groupby('possession_team')['match_id'].nunique().sort_values(ascending=False).to_frame()[:30])

                        match_id
possession_team
Barcelona                    518
Arsenal                       38
Real Madrid                   33
Atlético Madrid               29
Sevilla                       28
Valencia                      28
Espanyol                      25
Athletic Club                 24
Villarreal                    23
Real Betis                    22
Real Sociedad                 21
Getafe                        20
Osasuna                       19
England                       19
Croatia                       18
Celta Vigo                    18
Levante                       18
France                        18
RC Deportivo La Coruña        16
Málaga                        15
Belgium                       14
Spain                         14
Portugal                      13
Denmark                       13
Granada                       12
Real Zaragoza                 11
Racing Santander              11
Real Valladolid               11
Almería                       11
Argentina                     11

In [58]:
# in all_the_features_combined_df, group by possession_team.
pos_team = all_the_features_combined_df.groupby('possession_team')

# in pos_team, display a team
pos_team.get_group('Argentina').head()

,minutes,score_difference,distance_to_goal,angle_to_goal,foul_count_player,foul_count_team,vaep_offensive,prediction_regressor,prediction_classifier,actual_label,match_id,possession_team_id,possession_team,player_id,player
id,,,,,,,,,,,,,,,
e84e9b6f-154e-49ca-8252-913875a977c7,-1.518537,0.614112,0.875068,0.456097,-0.404798,-1.067673,0.128427,-0.006998,0,1,3869151,779,Argentina,3281.0,Aaron Mooy
aa01eafb-8093-473b-9cb7-233d87feb46b,-1.377034,0.614112,0.971835,0.870332,-0.404798,-0.052948,0.218888,1.007197,1,0,3869151,779,Argentina,5490.0,Jackson Irvine
1031a3ab-8f88-4b4d-a134-37b07c70835e,-0.563394,0.614112,1.147701,0.888631,-0.404798,0.454415,0.204214,0.966372,1,0,3869151,779,Argentina,15957.0,Miloš Degenek
8dc9c6bb-1813-4612-a40e-f5735543ddec,0.533252,-1.800865,-0.862206,1.833577,-0.404798,-0.560311,-0.698954,0.968461,1,1,3869151,779,Argentina,19597.0,Marcos Javier Acuña
044821c2-818d-488c-b012-3c84c410b465,0.745506,0.614112,-1.069415,-0.169565,1.865070,1.469140,0.265604,1.007239,1,1,3869151,779,Argentina,5490.0,Jackson Irvine

In [54]:
# sort fouls_per_match by 'fouls_per_match' and display the top 25 teams

fouls_per_match.sort_values(by='fouls_per_match', ascending=False).head(25)

    possession_team  match_id  fouls_per_match
209       Barcelona     68322               19
371       Barcelona     69299               18
379       Barcelona     69308               17
491       Barcelona    266357               16
442       Barcelona     70300               16
320       Barcelona     69241               16
299       Barcelona     69220               15
373       Barcelona     69302               15
693      Celta Vigo     68323               15
244       Barcelona     69141               14
395       Barcelona     69330               14
473       Barcelona    266142               14
443       Barcelona     70301               14
376       Barcelona     69305               14
407       Barcelona     70220               14
281       Barcelona     69184               13
496       Barcelona    266440               13
322       Barcelona     69243               13
324       Barcelona     69245               13
495       Barcelona    266433               13
411       Barcelona     70225               12
541       Barcelona    267077               12
424       Barcelona     70277               12
286       Barcelona     69195               12
544       Barcelona    267138               12